import Head from 'next/head';
import Image from 'next/image';
import NavBar from "../components/NavBar";
import Card from '../components/UI/Card';
// import DevIcon from "devicon-react-svg";

import CSS from '../components/svgs/icons/CSS';
import Express from '../components/svgs/icons/Express';
import Git from '../components/svgs/icons/Git';
import Gulp from '../components/svgs/icons/Gulp';
import Html from '../components/svgs/icons/Html';
import JavaScript from '../components/svgs/icons/JavaScript';
import Laravel from '../components/svgs/icons/Laravel';
import Markdown from '../components/svgs/icons/Markdown';
import MongoDB from '../components/svgs/icons/MongoDB';
import MySQL from '../components/svgs/icons/MySQL';
import NextJS from '../components/svgs/icons/NextJS';
import NodeJS from '../components/svgs/icons/NodeJS';
import PHP from '../components/svgs/icons/PHP';
import PostgreSQL from '../components/svgs/icons/PostgreSQL';
import ReactJS from '../components/svgs/icons/ReactJS';
import Redux from '../components/svgs/icons/Redux';
import SASS from '../components/svgs/icons/SASS';
import TypeScript from '../components/svgs/icons/TypeScript';
import Webpack from '../components/svgs/icons/Webpack';

import screenshot_01 from "../public/images/BlaZr-Gear-01.png";
import screenshot_02 from "../public/images/job-board-newt-01.png";
import screenshot_03 from "../public/images/zuitblog-01.png";
import screenshot_04 from "../public/images/SquadUp-Social-01.png";
import screenshot_05 from "../public/images/SquadUp-Social-02.png";
import screenshot_06 from "../public/images/SquadUp-Social-03.png";
import screenshot_07 from "../public/images/SquadUp-Social-04.png";
import screenshot_08 from "../public/images/SquadUp-Social-05.png";

const Home = () => {
  const handleContactForm = () => {
    console.log("Form submitted!Z")
  };
  let cards = [
    {
      title: "Blazr Gear",
      type: "E-Commerce",
      image: screenshot_01,
      tech: ["React", "Redux-Toolkit", "PostgreSQL", "ExpressJS", "JWT", "StripeAPI", "CloudinaryAPI", "MapboxAPI", "SendGrid", "NodeMailer"],
      description: "Blazr Gear allows users to pay with Stripe. JWTs are used for authenticating and setting authorization guards for admin access. Nodemailer and SendGrid is used to email a user of a successful purchase or when an order has been refunded. Additionally, this email service is used to reset a user's password. Users have the option to save cards they used in their purchases via the StripeAPI. Admins can review orders, create and update products, and edit admin permissions for other users."
    },
    {
      title: "Newt - Simple Job Search",
      type: "Job Board via Public API",
      image: screenshot_02,
      tech: ["NextJS" , "React Hooks", "FindworkAPI"],
      description: "Newt, a simple job board that fetches data from the Findwork public API. This is the first application I built using NextJS. This project was a means of learning some of the base features such as Server Side Rendering."
    },
    {
      title: "Zuit",
      type: "Blog",
      image: screenshot_03,
      tech: ["NextJS" , "React Hooks", "EditorJS", "MongoDB", "Mongoose"],
      description: "Zuit - a blog where users can share general thoughts, ideas and more importantly - code snippets with one another. React useReducer and useContext is used to keep track of state across all components in the app. Users can change the color of the blog from an assortment of themes. Authorization and authentication is kept inside of a cookie.",
    },
    {
      title: "SquadUp Social",
      type: "Social Media",
      image: screenshot_04,
      tech: ["React", "Redux", "PostgreSQL", "ExpressJS", "JWT", "CloudinaryAPI"],
      description: "First 'large' fullstack project I ever worked on without the aid of a video tutorial. This project allowed me to break out of the dreaded 'Tutorial Hell' once and for all. SquadUp is a social media site that allows users to share images and to send simple communications.",
    },
    {
      title: "The Den",
      type: "Restaurant",
      image: screenshot_05,
      tech: ["Gatsby", "Markdown", "JSON", "JamStack", "JWT", "CloudinaryAPI", "EmailJS"],
      description: "Designed for a restauraunt here in the heart of California. A redesign of a site that previously looked awful and could not work correctly in mobile browsers. At the time of rebuilding the site I was looking into static websites (JamStack). I chose to use GatsbyJS over NextJS, but I'd soon find out that I would not like the plugin system used by Gatsby all that much, but I did love the built in support for GraphQL which made fetching static data from JSON and Markdown files a breeze.",
    }
  ];
  return (
    <div className="container">
      <Head>
        <title>Jor-EL&apos;s Portfolio | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar/>
      <main className="main">
        <div className="">
          <section className="hero">
            <h2 className='hero__jumbo-text'>A Front End developer with Back End experience</h2>
{/* image goes here */}
            <div className="hero__img-container">
              <span>JS</span>
            </div>
            <h1 className="hero__name">
              Jor-EL Sanchez
            </h1>
          </section>
          <section className="skills">
            <div className="skills__content">
              <h2 className="skills__header">Primary Skills</h2>
              <div className="skills__desc">
                <p>Skilled in the following tech, as well as - JSON, Cloudinary, public APIs, Stripe, Fetch, and Axios.</p>
              </div>
              <div className="skills__icon-container">
                {/* <CSS/> */}
                <Express/>
                {/* <Git/> */}
                {/* <Html/> */}
                <MongoDB/>
                <JavaScript/>
                <Markdown/>
                <MySQL/>
                <NextJS/>
                {/* <NodeJS/> */}
                <PostgreSQL/>
                <ReactJS/>
                <Redux/>
                <SASS/>
              </div>
            </div>
            <div className="skills__content">
              <h2 className="skills__header">Familiar / Diving Into</h2>
              <div className="skills__desc">
                <p>Currently learning or somewhat familiar with the following tech (such as Photoshop).</p>
              </div>
              <div className="skills__icon-container">
                <Laravel/>
                <PHP/>
                <TypeScript/>
              </div>
            </div>
            <div className="skills__content">
              <h2 className="skills__header">Other Stuff I Know</h2>
              <div className="skills__desc">
                <p>Other tech I&apos;ve worked with: SendGrid, EmailJS and more.</p>
              </div>
              <div className="skills__icon-container">
            <Gulp/>
            <Webpack/>
              </div>
            </div>
          </section>
          <section className="projects">
            <h2 className="projects__header">
              Portfolio Projects
            </h2>
            <div className="projects__list">
              {cards.map((card, index) => (
                <div className="projects__list-item" key={index}>
                  <Card card={card} />
                </div>
              ))}
            </div>
          </section>
        </div>
      </main>
      <footer className="footer">
        <div className="footer__container">
          <div className="footer__contact">
            <h3>Want to contact me?</h3>
            <br />
            <div className="">
              <h2>E-Mail:</h2>
              <div className="email-address">
                <p>acemiranda13@att.net</p>
              </div>
            </div>
          </div>
          <form onSubmit={handleContactForm} className="footer__form form">
            <div className="form__group email">
              <input className='form__input' type="email" name='email' placeholder='Your E-mail' required/>
              <span className="underline"></span>
            </div>
            <div className="form__group subject">
              <input className='form__input' type="text" name='subject' placeholder='Subject' required/>
              <span className="underline"></span>
            </div>
            <div className="form__group text">
              <textarea className='form__textarea' type="text" name='message' placeholder='Message' required/>
            </div>
            <div className="footer__form-submit"></div>
          </form>
        </div>
        <div className="footer__copyright">
          <h6>Jor-EL Sanchez &copy; 2022</h6>
        </div>
      </footer>
    </div>
  )
}
export default Home;

/*
<div className="contact__section">
          <form className="form" onSubmit={sendEmail} data-netlify-recaptcha="true" data-netlify="true">
            <div className="form__item hidden">
              <input type="hidden" name="subject" className="form__input" value="Catering Quote" required/>
            </div>
            <div className="form__item">
              <label htmlFor="name" className="form__label">
                Your Name<span className="req">*</span>
              </label>
              <input type="text" name="name" className="form__input" placeholder="First Name (Last Name optional)" required/>
            </div>
            <div className="form__item">
              <label htmlFor="phone" className="form__label">
                Phone Number
              </label>
              <input type="tel" name="phone" className="form__input" pattern="[0-9]{3}-[0-9]{3}-[0-9]{4}" placeholder="123-456-7890"/>
            </div>
            <div className="form__item">
              <label htmlFor="email" className="form__label">
                Your Email Address<span className="req">*</span>
              </label>
              <input type="email" name="email" className="form__input" placeholder="email@mail.com" required/>
            </div>
            <div className="form__item">
              <label htmlFor="numpeople" className="form__label">
                How Many People?
              </label>
              <input type="number" name="numpeople" className="form__input" />
            </div>
            <div className="form__item">
              <label htmlFor="message" className="form__label">
                Message<span className="req">*</span>
              </label>
              <textarea name="message" className="form__textarea" id="" cols="30" rows="10" placeholder="Write your message." required></textarea>
            </div>
            <div className="form__item">
              <div data-netlify-recaptcha="true" className="contact__captcha"></div>
            </div>
            <div className="form__footer">
              <input type="submit" className="btn btn-primary ms-mr ms-mt" value="Send Message" />
            </div>
          </form>
        </div>
*/