import { useState, useRef, useContext } from "react";
import { ThemeContext } from "use-theme-switcher";
import Head from 'next/head';
import Image from 'next/image';
import NavBar from "../components/NavBar";
import Skills from "../components/sections/Skills";
import Projects from "../components/sections/Projects";
import Footer from "../components/sections/Footer";
import Dots from "../components/svgs/shapes/Dots";
import avatar from "../public/images/avatars/24633082.jpg";
import Computer from "../public/svg/undraw_programming_re_kg9v.svg";
import Blob01 from "../components/svgs/shapes/Blob01";
import Circle01 from "../components/svgs/shapes/Circle01";
import Circle02 from "../components/svgs/shapes/Circle02";
// import Computer from "../public/png/undraw_Programming_re_kg9v.png";

const Home = () => {
  const { theme, switchTheme } = useContext(ThemeContext);
  const [showThemes, isShowThemes] = useState(false);
  
  return (
    <div className="container">
      <Head>
        <title>Jor-EL&apos;s Portfolio | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar showThemes={showThemes} isShowThemes={isShowThemes}/>
      <main className="main">
        <div className="">
          <section className="hero">
            <h2 className='hero__jumbo-text'>A Front End developer with Back End experience</h2>
            <div className="decor">
              <div className="decor__slice">
                <div className="decor__group--01">
                  {/* <Blob01 /> */}
                  <div className="decor__svg-computer">
                    <Image
                      src={Computer}
                      className="hero__img"
                      alt="project screen"
                      layout="responsive"
                      height={180}
                      width={180}
                    />
                  </div>
                </div>
              </div>
              <Circle01 />
              <Circle02 />
              <Dots />
              <div className="hero__img-container">
                <Image
                  src={avatar}
                  className="hero__img"
                  alt="project screen"
                  layout="responsive"
                  height={180}
                  width={180}
                />
              </div>
            </div>
            <h1 className="hero__name">
              Jor-EL Sanchez
            </h1>
            <div className="hero__buffer"></div>
          </section>
          <Skills />
          <Projects />
        </div>
      </main>
      <Footer />
    </div>
  )
}
export default Home;
// TODO create a character limit of 400 or 300 characters.